services:
  postgres-db:
    image: postgres:latest
    container_name: docker-postgres-db-1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 10s
