/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * license agreements; and to You under the Apache License, version 2.0:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * This file is part of the Apache Pekko project, which was derived from Akka.
 */

package org.apache.pekko.projection.r2dbc

import org.apache.pekko.projection.r2dbc.internal.mysql.MySQLR2dbcOffsetStore
import org.scalatest.TestSuite
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

/**
 * Unit tests for the SQL strings generated by [[MySQLR2dbcOffsetStore]].
 *
 * These tests run without a database and are intended to catch regressions such as the
 * `NOT CONCAT(...) IN` vs `CONCAT(...) NOT IN` operator-placement bug fixed in
 * https://github.com/apache/pekko-projection/pull/495.
 */
class MySQLR2dbcOffsetStoreSqlSpec extends AnyWordSpec with TestSuite with Matchers {

  private val table = "projection.timestamp_offset"

  "MySQLR2dbcOffsetStore.buildDeleteOldTimestampOffsetsSql" should {

    "produce a simple DELETE when there are no exclusions" in {
      val sql = MySQLR2dbcOffsetStore.buildDeleteOldTimestampOffsetsSql(table, 0)
      sql should include("DELETE FROM")
      sql should include(table)
      sql should include("timestamp_offset < ?")
      sql should not include "NOT IN"
      sql should not include "CONCAT"
    }

    "produce a DELETE with CONCAT…NOT IN for a single exclusion" in {
      val sql = MySQLR2dbcOffsetStore.buildDeleteOldTimestampOffsetsSql(table, 1)
      sql should include("DELETE FROM")
      sql should include(table)
      sql should include("timestamp_offset < ?")
      // Operator must be `CONCAT(…) NOT IN`, not `NOT CONCAT(…) IN`
      sql should include("CONCAT(persistence_id, '-', seq_nr) NOT IN")
      sql should not include "NOT CONCAT"
      sql should endWith("NOT IN (?)")
    }

    "produce a DELETE with CONCAT…NOT IN for multiple exclusions" in {
      val sql = MySQLR2dbcOffsetStore.buildDeleteOldTimestampOffsetsSql(table, 3)
      sql should include("DELETE FROM")
      sql should include(table)
      sql should include("timestamp_offset < ?")
      sql should include("CONCAT(persistence_id, '-', seq_nr) NOT IN")
      sql should not include "NOT CONCAT"
      sql should endWith("NOT IN (?, ?, ?)")
    }

    "include the correct number of placeholders" in {
      for (n <- 1 to 5) {
        val sql = MySQLR2dbcOffsetStore.buildDeleteOldTimestampOffsetsSql(table, n)
        val expectedPlaceholders = Seq.fill(n)("?").mkString(", ")
        sql should include(s"NOT IN ($expectedPlaceholders)")
      }
    }

    "include the table name in the generated SQL" in {
      val customTable = "my_schema.my_projection_offset"
      val sql = MySQLR2dbcOffsetStore.buildDeleteOldTimestampOffsetsSql(customTable, 2)
      sql should startWith(s"DELETE FROM $customTable")
    }
  }
}
